txt = '''.fas,.fa-0::before,.fa-1::before,.fa-2::before,.fa-3::before,.fa-4::before,.fa-5::before,.fa-6::before,.fa-7::before,.fa-8::before,.fa-9::before,.fa-fill-drip::before,.fa-arrows-to-circle::before,.fa-chevron-circle-right::before, .fa-circle-chevron-right::before,
.fa-at::before,.fa-trash-alt::before, .fa-trash-can::before,.fa-text-height::before,.fa-user-times::before, .fa-user-xmark::before,.fa-stethoscope::before,.fa-comment-alt::before, .fa-message::before,.fa-info::before,.fa-compress-alt::before, .fa-down-left-and-up-right-to-center::before,.fa-explosion::before,.fa-file-alt::before, .fa-file-lines::before, .fa-file-text::before,.fa-wave-square::before,.fa-ring::before,.fa-building-un::before,.fa-dice-three::before,.fa-calendar-alt::before, .fa-calendar-days::before,.fa-anchor-circle-check::before,.fa-building-circle-arrow-right::before,.fa-volleyball-ball::before, .fa-volleyball::before,.fa-arrows-up-to-line::before,.fa-sort-desc::before, .fa-sort-down::before,.fa-circle-minus::before, .fa-minus-circle::before,.fa-door-open::before,.fa-right-from-bracket::before, .fa-sign-out-alt::before,.fa-atom::before,.fa-soap::before,.fa-heart-music-camera-bolt::before, .fa-icons::before,.fa-microphone-alt-slash::before, .fa-microphone-lines-slash::before,.fa-bridge-circle-check::before,.fa-pump-medical::before,.fa-fingerprint::before,.fa-hand-point-right::before,.fa-magnifying-glass-location::before, .fa-search-location::before,
.fa-forward-step::before, .fa-step-forward::before,.fa-face-smile-beam::before, .fa-smile-beam::before,.fa-flag-checkered::before,.fa-football-ball::before, .fa-football::before,.fa-school-circle-exclamation::before,.fa-crop::before,.fa-angle-double-down::before, .fa-angles-down::before,.fa-users-rectangle::before,.fa-people-roof::before,.fa-people-line::before,.fa-beer-mug-empty::before, .fa-beer::before,.fa-diagram-predecessor::before,.fa-arrow-up-long::before, .fa-long-arrow-up::before,.fa-burn::before, .fa-fire-flame-simple::before,.fa-male::before, .fa-person::before,.fa-laptop::before,.fa-file-csv::before,.fa-menorah::before,.fa-truck-plane::before,.fa-record-vinyl::before,.fa-face-grin-stars::before, .fa-grin-stars::before,.fa-bong::before,.fa-pastafarianism::before, .fa-spaghetti-monster-flying::before,.fa-arrow-down-up-across-line::before,.fa-spoon::before, .fa-utensil-spoon::before,.fa-jar-wheat::before,.fa-envelopes-bulk::before, .fa-mail-bulk::before,.fa-file-circle-exclamation::before,.fa-circle-h::before, .fa-hospital-symbol::before,.fa-pager::before,.fa-address-book::before, .fa-contact-book::before,.fa-strikethrough::before,
.fa-k::before,.fa-landmark-flag::before,.fa-pencil-alt::before, .fa-pencil::before,.fa-backward::before,.fa-caret-right::before,.fa-comments::before,.fa-file-clipboard::before, .fa-paste::before,.fa-code-pull-request::before,.fa-clipboard-list::before,.fa-truck-loading::before, .fa-truck-ramp-box::before,.fa-user-check::before,.fa-vial-virus::before,.fa-sheet-plastic::before,.fa-blog::before,.fa-user-ninja::before,.fa-person-arrow-up-from-line::before,.fa-scroll-torah::before, .fa-torah::before,.fa-broom-ball::before, .fa-quidditch-broom-ball::before, .fa-quidditch::before,.fa-toggle-off::before,.fa-archive::before, .fa-box-archive::before,.fa-person-drowning::before,.fa-arrow-down-9-1::before, .fa-sort-numeric-desc::before, .fa-sort-numeric-down-alt::before,.fa-face-grin-tongue-squint::before, .fa-grin-tongue-squint::before,.fa-spray-can::before,.fa-truck-monster::before,.fa-w::before,.fa-earth-africa::before, .fa-globe-africa::before,.fa-rainbow::before,.fa-circle-notch::before,.fa-tablet-alt::before, .fa-tablet-screen-button::before,.fa-paw::before,.fa-cloud::before,
.fa-trowel-bricks::before,.fa-face-flushed::before, .fa-flushed::before,.fa-hospital-user::before,.fa-tent-arrow-left-right::before,.fa-gavel::before, .fa-legal::before,.fa-binoculars::before,.fa-microphone-slash::before,.fa-box-tissue::before,.fa-motorcycle::before,.fa-bell-concierge::before, .fa-concierge-bell::before,.fa-pen-ruler::before, .fa-pencil-ruler::before,.fa-people-arrows-left-right::before, .fa-people-arrows::before,.fa-mars-and-venus-burst::before,.fa-caret-square-right::before, .fa-square-caret-right::before,.fa-cut::before, .fa-scissors::before,.fa-sun-plant-wilt::before,.fa-toilets-portable::before,.fa-hockey-puck::before,.fa-table::before,.fa-magnifying-glass-arrow-right::before,.fa-digital-tachograph::before, .fa-tachograph-digital::before,.fa-users-slash::before,.fa-clover::before,.fa-mail-reply::before, .fa-reply::before,.fa-star-and-crescent::before,.fa-house-fire::before,.fa-minus-square::before, .fa-square-minus::before,.fa-helicopter::before,.fa-compass::before,.fa-caret-square-down::before, .fa-square-caret-down::before,.fa-file-circle-question::before,.fa-laptop-code::before,
.fa-swatchbook::before,.fa-prescription-bottle::before,.fa-bars::before, .fa-navicon::before,.fa-people-group::before,.fa-hourglass-3::before, .fa-hourglass-end::before,.fa-heart-broken::before, .fa-heart-crack::before,.fa-external-link-square-alt::before, .fa-square-up-right::before,.fa-face-kiss-beam::before, .fa-kiss-beam::before,.fa-film::before,.fa-ruler-horizontal::before,.fa-people-robbery::before,.fa-lightbulb::before,.fa-caret-left::before,.fa-circle-exclamation::before, .fa-exclamation-circle::before,.fa-school-circle-xmark::before,.fa-arrow-right-from-bracket::before, .fa-sign-out::before,.fa-chevron-circle-down::before, .fa-circle-chevron-down::before,.fa-unlock-alt::before, .fa-unlock-keyhole::before,.fa-cloud-showers-heavy::before,.fa-headphones-alt::before, .fa-headphones-simple::before,.fa-sitemap::before,.fa-circle-dollar-to-slot::before, .fa-donate::before,.fa-memory::before,.fa-road-spikes::before,.fa-fire-burner::before,.fa-flag::before,.fa-hanukiah::before,.fa-feather::before,.fa-volume-down::before, .fa-volume-low::before,.fa-comment-slash::before,.fa-cloud-sun-rain::before,.fa-compress::before,
.fa-wheat-alt::before, .fa-wheat-awn::before,.fa-ankh::before,.fa-hands-holding-child::before,.fa-asterisk::before,.fa-check-square::before, .fa-square-check::before,.fa-peseta-sign::before,.fa-header::before, .fa-heading::before,.fa-ghost::before,.fa-list-squares::before, .fa-list::before,.fa-phone-square-alt::before, .fa-square-phone-flip::before,.fa-cart-plus::before,.fa-gamepad::before,.fa-circle-dot::before, .fa-dot-circle::before,.fa-dizzy::before, .fa-face-dizzy::before,.fa-egg::before,.fa-house-medical-circle-xmark::before,.fa-campground::before,.fa-folder-plus::before,.fa-futbol-ball::before, .fa-futbol::before, .fa-soccer-ball::before,.fa-paint-brush::before, .fa-paintbrush::before,.fa-lock::before,.fa-gas-pump::before,.fa-hot-tub-person::before, .fa-hot-tub::before,.fa-map-location::before, .fa-map-marked::before,.fa-house-flood-water::before,.fa-tree::before,.fa-bridge-lock::before,.fa-sack-dollar::before,.fa-edit::before, .fa-pen-to-square::before,.fa-car-side::before,.fa-share-alt::before, .fa-share-nodes::before,.fa-heart-circle-minus::before,
.fa-hourglass-2::before, .fa-hourglass-half::before,.fa-microscope::before,.fa-sink::before,.fa-bag-shopping::before, .fa-shopping-bag::before,.fa-arrow-down-z-a::before, .fa-sort-alpha-desc::before, .fa-sort-alpha-down-alt::before,.fa-mitten::before,.fa-person-rays::before,.fa-users::before,.fa-eye-slash::before,.fa-flask-vial::before,.fa-hand-paper::before, .fa-hand::before,.fa-om::before,.fa-worm::before,.fa-house-circle-xmark::before,.fa-plug::before,.fa-chevron-up::before,.fa-hand-spock::before,.fa-stopwatch::before,.fa-face-kiss::before, .fa-kiss::before,.fa-bridge-circle-xmark::before,.fa-face-grin-tongue::before, .fa-grin-tongue::before,.fa-chess-bishop::before,.fa-face-grin-wink::before, .fa-grin-wink::before,.fa-deaf::before, .fa-deafness::before, .fa-ear-deaf::before, .fa-hard-of-hearing::before,.fa-road-circle-check::before,.fa-dice-five::before,.fa-rss-square::before, .fa-square-rss::before,.fa-land-mine-on::before,.fa-i-cursor::before,.fa-stamp::before,.fa-stairs::before,.fa-i::before,
.fa-hryvnia-sign::before, .fa-hryvnia::before,.fa-pills::before,.fa-face-grin-wide::before, .fa-grin-alt::before,.fa-tooth::before,.fa-v::before,.fa-bangladeshi-taka-sign::before,.fa-bicycle::before,.fa-rod-asclepius::before, .fa-rod-snake::before, .fa-staff-aesculapius::before, .fa-staff-snake::before,.fa-head-side-cough-slash::before,.fa-ambulance::before, .fa-truck-medical::before,.fa-wheat-awn-circle-exclamation::before,.fa-snowman::before,.fa-mortar-pestle::before,.fa-road-barrier::before,.fa-school::before,.fa-igloo::before,.fa-joint::before,.fa-angle-right::before,.fa-horse::before,.fa-q::before,.fa-g::before,.fa-notes-medical::before,.fa-temperature-2::before, .fa-temperature-half::before, .fa-thermometer-2::before, .fa-thermometer-half::before,.fa-dong-sign::before,.fa-capsules::before,.fa-poo-bolt::before, .fa-poo-storm::before,.fa-face-frown-open::before, .fa-frown-open::before,.fa-hand-point-up::before,.fa-money-bill::before,.fa-bookmark::before,.fa-align-justify::before,.fa-umbrella-beach::before,
.fa-helmet-un::before,.fa-bullseye::before,.fa-bacon::before,.fa-hand-point-down::before,.fa-arrow-up-from-bracket::before,.fa-folder-blank::before, .fa-folder::before,.fa-file-medical-alt::before, .fa-file-waveform::before,.fa-radiation::before,.fa-chart-simple::before,.fa-mars-stroke::before,.fa-vial::before,.fa-dashboard::before, .fa-gauge-med::before, .fa-gauge::before, .fa-tachometer-alt-average::before,.fa-magic-wand-sparkles::before, .fa-wand-magic-sparkles::before,.fa-e::before,.fa-pen-alt::before, .fa-pen-clip::before,.fa-bridge-circle-exclamation::before,.fa-user::before,.fa-school-circle-check::before,.fa-dumpster::before,.fa-shuttle-van::before, .fa-van-shuttle::before,.fa-building-user::before,.fa-caret-square-left::before, .fa-square-caret-left::before,.fa-highlighter::before,.fa-key::before,.fa-bullhorn::before,.fa-globe::before,.fa-synagogue::before,.fa-person-half-dress::before,.fa-road-bridge::before,.fa-location-arrow::before,.fa-c::before,.fa-tablet-button::before,
.fa-building-lock::before,.fa-pizza-slice::before,.fa-money-bill-wave::before,.fa-area-chart::before, .fa-chart-area::before,.fa-house-flag::before,.fa-person-circle-minus::before,.fa-ban::before, .fa-cancel::before,.fa-camera-rotate::before,.fa-air-freshener::before, .fa-spray-can-sparkles::before,.fa-star::before,.fa-repeat::before,.fa-cross::before,.fa-box::before,.fa-venus-mars::before,.fa-arrow-pointer::before, .fa-mouse-pointer::before,.fa-expand-arrows-alt::before, .fa-maximize::before,.fa-charging-station::before,.fa-shapes::before, .fa-triangle-circle-square::before,.fa-random::before, .fa-shuffle::before,.fa-person-running::before, .fa-running::before,.fa-mobile-retro::before,.fa-grip-lines-vertical::before,.fa-spider::before,.fa-hands-bound::before,.fa-file-invoice-dollar::before,.fa-plane-circle-exclamation::before,.fa-x-ray::before,.fa-spell-check::before,.fa-slash::before,.fa-computer-mouse::before, .fa-mouse::before,.fa-arrow-right-to-bracket::before, .fa-sign-in::before,.fa-shop-slash::before, .fa-store-alt-slash::before,
.fa-server::before,.fa-virus-covid-slash::before,.fa-shop-lock::before,.fa-hourglass-1::before, .fa-hourglass-start::before,.fa-blender-phone::before,.fa-building-wheat::before,.fa-person-breastfeeding::before,.fa-right-to-bracket::before, .fa-sign-in-alt::before,.fa-venus::before,.fa-passport::before,.fa-heart-pulse::before, .fa-heartbeat::before,.fa-people-carry-box::before, .fa-people-carry::before,.fa-temperature-high::before,.fa-microchip::before,.fa-crown::before,.fa-weight-hanging::before,.fa-xmarks-lines::before,.fa-file-prescription::before,.fa-weight-scale::before, .fa-weight::before,.fa-user-friends::before, .fa-user-group::before,.fa-arrow-up-a-z::before, .fa-sort-alpha-up::before,.fa-chess-knight::before,.fa-face-laugh-squint::before, .fa-laugh-squint::before,.fa-wheelchair::before,.fa-arrow-circle-up::before, .fa-circle-arrow-up::before,.fa-toggle-on::before,.fa-person-walking::before, .fa-walking::before,.fa-l::before,.fa-fire::before,.fa-bed-pulse::before, .fa-procedures::before,.fa-shuttle-space::before, .fa-space-shuttle::before,.fa-face-laugh::before, .fa-laugh::before,
.fa-folder-open::before,.fa-heart-circle-plus::before,.fa-code-fork::before,.fa-city::before,.fa-microphone-alt::before, .fa-microphone-lines::before,.fa-pepper-hot::before,.fa-unlock::before,.fa-colon-sign::before,.fa-headset::before,.fa-store-slash::before,.fa-road-circle-xmark::before,.fa-user-minus::before,.fa-mars-stroke-up::before, .fa-mars-stroke-v::before,.fa-champagne-glasses::before, .fa-glass-cheers::before,.fa-clipboard::before,.fa-house-circle-exclamation::before,.fa-file-arrow-up::before, .fa-file-upload::before,.fa-wifi-3::before, .fa-wifi-strong::before, .fa-wifi::before,.fa-bath::before, .fa-bathtub::before,.fa-underline::before,.fa-user-edit::before, .fa-user-pen::before,.fa-signature::before,.fa-stroopwafel::before,.fa-bold::before,.fa-anchor-lock::before,.fa-building-ngo::before,.fa-manat-sign::before,.fa-not-equal::before,.fa-border-style::before, .fa-border-top-left::before,.fa-map-location-dot::before, .fa-map-marked-alt::before,.fa-jedi::before,.fa-poll::before, .fa-square-poll-vertical::before,
.fa-mug-hot::before,.fa-battery-car::before, .fa-car-battery::before,.fa-gift::before,.fa-dice-two::before,.fa-chess-queen::before,.fa-glasses::before,.fa-chess-board::before,.fa-building-circle-check::before,.fa-person-chalkboard::before,.fa-mars-stroke-h::before, .fa-mars-stroke-right::before,.fa-hand-back-fist::before, .fa-hand-rock::before,.fa-caret-square-up::before, .fa-square-caret-up::before,.fa-cloud-showers-water::before,.fa-bar-chart::before, .fa-chart-bar::before,.fa-hands-bubbles::before, .fa-hands-wash::before,.fa-less-than-equal::before,.fa-train::before,.fa-eye-low-vision::before, .fa-low-vision::before,.fa-crow::before,.fa-sailboat::before,.fa-window-restore::before,.fa-plus-square::before, .fa-square-plus::before,.fa-torii-gate::before,.fa-frog::before,.fa-bucket::before,.fa-image::before,.fa-microphone::before,.fa-cow::before,.fa-caret-up::before,.fa-screwdriver::before,.fa-folder-closed::before,.fa-house-tsunami::before,
.fa-square-nfi::before,.fa-arrow-up-from-ground-water::before,.fa-glass-martini-alt::before, .fa-martini-glass::before,.fa-rotate-back::before, .fa-rotate-backward::before, .fa-rotate-left::before, .fa-undo-alt::before,.fa-columns::before, .fa-table-columns::before,.fa-lemon::before,.fa-head-side-mask::before,.fa-handshake::before,.fa-gem::before,.fa-dolly-box::before, .fa-dolly::before,.fa-smoking::before,.fa-compress-arrows-alt::before, .fa-minimize::before,.fa-monument::before,.fa-snowplow::before,.fa-angle-double-right::before, .fa-angles-right::before,.fa-cannabis::before,.fa-circle-play::before, .fa-play-circle::before,.fa-tablets::before,.fa-ethernet::before,.fa-eur::before, .fa-euro-sign::before, .fa-euro::before,.fa-chair::before,.fa-check-circle::before, .fa-circle-check::before,.fa-circle-stop::before, .fa-stop-circle::before,.fa-compass-drafting::before, .fa-drafting-compass::before,.fa-plate-wheat::before,.fa-icicles::before,.fa-person-shelter::before,.fa-neuter::before,.fa-id-badge::before,.fa-marker::before,.fa-face-laugh-beam::before, .fa-laugh-beam::before,.fa-helicopter-symbol::before,
.fa-universal-access::before,.fa-chevron-circle-up::before, .fa-circle-chevron-up::before,.fa-lari-sign::before,.fa-volcano::before,.fa-person-walking-dashed-line-arrow-right::before,.fa-gbp::before, .fa-pound-sign::before, .fa-sterling-sign::before,.fa-viruses::before,.fa-square-person-confined::before,.fa-user-tie::before,.fa-arrow-down-long::before, .fa-long-arrow-down::before,.fa-tent-arrow-down-to-line::before,.fa-certificate::before,.fa-mail-reply-all::before, .fa-reply-all::before,.fa-suitcase::before,.fa-person-skating::before, .fa-skating::before,.fa-filter-circle-dollar::before, .fa-funnel-dollar::before,.fa-camera-retro::before,.fa-arrow-circle-down::before, .fa-circle-arrow-down::before,.fa-arrow-right-to-file::before, .fa-file-import::before,.fa-external-link-square::before, .fa-square-arrow-up-right::before,.fa-box-open::before,.fa-scroll::before,.fa-spa::before,.fa-location-pin-lock::before,.fa-pause::before,.fa-hill-avalanche::before,.fa-temperature-0::before, .fa-temperature-empty::before, .fa-thermometer-0::before, .fa-thermometer-empty::before,.fa-bomb::before,.fa-registered::before,.fa-address-card::before, .fa-contact-card::before, .fa-vcard::before,.fa-balance-scale-right::before, .fa-scale-unbalanced-flip::before,.fa-subscript::before,
.fa-diamond-turn-right::before, .fa-directions::before,.fa-burst::before,.fa-house-laptop::before, .fa-laptop-house::before,.fa-face-tired::before, .fa-tired::before,.fa-money-bills::before,.fa-smog::before,.fa-crutch::before,.fa-cloud-arrow-up::before, .fa-cloud-upload-alt::before, .fa-cloud-upload::before,.fa-palette::before,.fa-arrows-turn-right::before,.fa-vest::before,.fa-ferry::before,.fa-arrows-down-to-people::before,.fa-seedling::before, .fa-sprout::before,.fa-arrows-alt-h::before, .fa-left-right::before,.fa-boxes-packing::before,.fa-arrow-circle-left::before, .fa-circle-arrow-left::before,.fa-group-arrows-rotate::before,.fa-bowl-food::before,.fa-candy-cane::before,.fa-arrow-down-wide-short::before, .fa-sort-amount-asc::before, .fa-sort-amount-down::before,.fa-cloud-bolt::before, .fa-thunderstorm::before,.fa-remove-format::before, .fa-text-slash::before,.fa-face-smile-wink::before, .fa-smile-wink::before,.fa-file-word::before,.fa-file-powerpoint::before,.fa-arrows-h::before, .fa-arrows-left-right::before,.fa-house-lock::before,.fa-cloud-arrow-down::before, .fa-cloud-download-alt::before, .fa-cloud-download::before,.fa-children::before,.fa-blackboard::before, .fa-chalkboard::before,.fa-user-alt-slash::before, .fa-user-large-slash::before,
.fa-envelope-open::before,.fa-handshake-alt-slash::before, .fa-handshake-simple-slash::before,.fa-mattress-pillow::before,.fa-guarani-sign::before,.fa-arrows-rotate::before, .fa-refresh::before, .fa-sync::before,.fa-fire-extinguisher::before,.fa-cruzeiro-sign::before,.fa-greater-than-equal::before,.fa-shield-alt::before, .fa-shield-halved::before,.fa-atlas::before, .fa-book-atlas::before,.fa-virus::before,.fa-envelope-circle-check::before,.fa-layer-group::before,.fa-arrows-to-dot::before,.fa-archway::before,.fa-heart-circle-check::before,.fa-house-chimney-crack::before, .fa-house-damage::before,.fa-file-archive::before, .fa-file-zipper::before,.fa-square::before,.fa-glass-martini::before, .fa-martini-glass-empty::before,.fa-couch::before,.fa-cedi-sign::before,.fa-italic::before,.fa-church::before,.fa-comments-dollar::before,.fa-democrat::before,.fa-z::before,.fa-person-skiing::before, .fa-skiing::before,.fa-road-lock::before,.fa-a::before,.fa-temperature-arrow-down::before, .fa-temperature-down::before,.fa-feather-alt::before, .fa-feather-pointed::before,
.fa-p::before,.fa-snowflake::before,.fa-newspaper::before,.fa-ad::before, .fa-rectangle-ad::before,.fa-arrow-circle-right::before, .fa-circle-arrow-right::before,.fa-filter-circle-xmark::before,.fa-locust::before,.fa-sort::before, .fa-unsorted::before,.fa-list-1-2::before, .fa-list-numeric::before, .fa-list-ol::before,.fa-person-dress-burst::before,.fa-money-check-alt::before, .fa-money-check-dollar::before,.fa-vector-square::before,.fa-bread-slice::before,.fa-language::before,.fa-face-kiss-wink-heart::before, .fa-kiss-wink-heart::before,.fa-filter::before,.fa-question::before,.fa-file-signature::before,.fa-arrows-alt::before, .fa-up-down-left-right::before,.fa-house-chimney-user::before,.fa-hand-holding-heart::before,.fa-puzzle-piece::before,.fa-money-check::before,.fa-star-half-alt::before, .fa-star-half-stroke::before,.fa-code::before,.fa-glass-whiskey::before, .fa-whiskey-glass::before,.fa-building-circle-exclamation::before,.fa-magnifying-glass-chart::before,.fa-arrow-up-right-from-square::before, .fa-external-link::before,.fa-cubes-stacked::before,.fa-krw::before, .fa-won-sign::before, .fa-won::before,.fa-virus-covid::before,
.fa-austral-sign::before,.fa-f::before,.fa-leaf::before,.fa-road::before,.fa-cab::before, .fa-taxi::before,.fa-person-circle-plus::before,.fa-chart-pie::before, .fa-pie-chart::before,.fa-bolt-lightning::before,.fa-sack-xmark::before,.fa-file-excel::before,.fa-file-contract::before,.fa-fish-fins::before,.fa-building-flag::before,.fa-face-grin-beam::before, .fa-grin-beam::before,.fa-object-ungroup::before,.fa-poop::before,.fa-location-pin::before, .fa-map-marker::before,.fa-kaaba::before,.fa-toilet-paper::before,.fa-hard-hat::before, .fa-hat-hard::before, .fa-helmet-safety::before,.fa-eject::before,.fa-arrow-alt-circle-right::before, .fa-circle-right::before,.fa-plane-circle-check::before,.fa-face-rolling-eyes::before, .fa-meh-rolling-eyes::before,.fa-object-group::before,.fa-chart-line::before, .fa-line-chart::before,.fa-mask-ventilator::before,.fa-arrow-right::before,.fa-map-signs::before, .fa-signs-post::before,.fa-cash-register::before,.fa-person-circle-question::before,.fa-h::before,
.fa-tarp::before,.fa-screwdriver-wrench::before, .fa-tools::before,.fa-arrows-to-eye::before,.fa-plug-circle-bolt::before,.fa-heart::before,.fa-mars-and-venus::before,.fa-home-user::before, .fa-house-user::before,.fa-dumpster-fire::before,.fa-house-crack::before,.fa-cocktail::before, .fa-martini-glass-citrus::before,.fa-face-surprise::before, .fa-surprise::before,.fa-bottle-water::before,.fa-circle-pause::before, .fa-pause-circle::before,.fa-toilet-paper-slash::before,.fa-apple-alt::before, .fa-apple-whole::before,.fa-kitchen-set::before,.fa-r::before,.fa-temperature-1::before, .fa-temperature-quarter::before, .fa-thermometer-1::before, .fa-thermometer-quarter::before,.fa-cube::before,.fa-bitcoin-sign::before,.fa-shield-dog::before,.fa-solar-panel::before,.fa-lock-open::before,.fa-elevator::before,.fa-money-bill-transfer::before,.fa-money-bill-trend-up::before,.fa-house-flood-water-circle-arrow-right::before,.fa-poll-h::before, .fa-square-poll-horizontal::before,.fa-circle::before,.fa-backward-fast::before, .fa-fast-backward::before,.fa-recycle::before,.fa-user-astronaut::before,
.fa-plane-slash::before,.fa-trademark::before,.fa-basketball-ball::before, .fa-basketball::before,.fa-satellite-dish::before,.fa-arrow-alt-circle-up::before, .fa-circle-up::before,.fa-mobile-alt::before, .fa-mobile-screen-button::before,.fa-volume-high::before, .fa-volume-up::before,.fa-users-rays::before,.fa-wallet::before,.fa-clipboard-check::before,.fa-file-audio::before,.fa-burger::before, .fa-hamburger::before,.fa-wrench::before,.fa-bugs::before,.fa-rupee-sign::before, .fa-rupee::before,.fa-file-image::before,.fa-circle-question::before, .fa-question-circle::before,.fa-plane-departure::before,.fa-handshake-slash::before,.fa-book-bookmark::before,.fa-code-branch::before,.fa-hat-cowboy::before,.fa-bridge::before,.fa-phone-alt::before, .fa-phone-flip::before,.fa-truck-front::before,.fa-cat::before,.fa-anchor-circle-exclamation::before,.fa-truck-field::before,.fa-route::before,.fa-clipboard-question::before,.fa-panorama::before,.fa-comment-medical::before,
.fa-teeth-open::before,.fa-file-circle-minus::before,.fa-tags::before,.fa-wine-glass::before,.fa-fast-forward::before, .fa-forward-fast::before,.fa-face-meh-blank::before, .fa-meh-blank::before,.fa-parking::before, .fa-square-parking::before,.fa-house-signal::before,.fa-bars-progress::before, .fa-tasks-alt::before,.fa-faucet-drip::before,.fa-cart-flatbed::before, .fa-dolly-flatbed::before,.fa-ban-smoking::before, .fa-smoking-ban::before,.fa-terminal::before,.fa-mobile-button::before,.fa-house-medical-flag::before,.fa-basket-shopping::before, .fa-shopping-basket::before,.fa-tape::before,.fa-bus-alt::before, .fa-bus-simple::before,.fa-eye::before,.fa-face-sad-cry::before, .fa-sad-cry::before,.fa-audio-description::before,.fa-person-military-to-person::before,.fa-file-shield::before,.fa-user-slash::before,.fa-pen::before,.fa-tower-observation::before,.fa-file-code::before,.fa-signal-5::before, .fa-signal-perfect::before, .fa-signal::before,.fa-bus::before,.fa-heart-circle-xmark::before,.fa-home-lg::before, .fa-house-chimney::before,.fa-window-maximize::before,
.fa-face-frown::before, .fa-frown::before,.fa-prescription::before,.fa-shop::before, .fa-store-alt::before,.fa-floppy-disk::before, .fa-save::before,.fa-vihara::before,.fa-balance-scale-left::before, .fa-scale-unbalanced::before,.fa-sort-asc::before, .fa-sort-up::before,.fa-comment-dots::before, .fa-commenting::before,.fa-plant-wilt::before,.fa-diamond::before,.fa-face-grin-squint::before, .fa-grin-squint::before,.fa-hand-holding-dollar::before, .fa-hand-holding-usd::before,.fa-bacterium::before,.fa-hand-pointer::before,.fa-drum-steelpan::before,.fa-hand-scissors::before,.fa-hands-praying::before, .fa-praying-hands::before,.fa-arrow-right-rotate::before, .fa-arrow-rotate-forward::before, .fa-arrow-rotate-right::before, .fa-redo::before,.fa-biohazard::before,.fa-location-crosshairs::before, .fa-location::before,.fa-mars-double::before,.fa-child-dress::before,.fa-users-between-lines::before,.fa-lungs-virus::before,.fa-face-grin-tears::before, .fa-grin-tears::before,.fa-phone::before,.fa-calendar-times::before, .fa-calendar-xmark::before,.fa-child-reaching::before,.fa-head-side-virus::before,.fa-user-cog::before, .fa-user-gear::before,.fa-arrow-up-1-9::before, .fa-sort-numeric-up::before,.fa-door-closed::before,
.fa-shield-virus::before,.fa-dice-six::before,.fa-mosquito-net::before,.fa-bridge-water::before,.fa-person-booth::before,.fa-text-width::before,.fa-hat-wizard::before,.fa-pen-fancy::before,.fa-digging::before, .fa-person-digging::before,.fa-trash::before,.fa-gauge-simple-med::before, .fa-gauge-simple::before, .fa-tachometer-average::before,.fa-book-medical::before,.fa-poo::before,.fa-quote-right-alt::before, .fa-quote-right::before,.fa-shirt::before, .fa-t-shirt::before, .fa-tshirt::before,.fa-cubes::before,.fa-divide::before,.fa-tenge-sign::before, .fa-tenge::before,.fa-headphones::before,.fa-hands-holding::before,.fa-hands-clapping::before,.fa-republican::before,.fa-arrow-left::before,.fa-person-circle-xmark::before,.fa-ruler::before,.fa-align-left::before,.fa-dice-d6::before,.fa-restroom::before,.fa-j::before,.fa-users-viewfinder::before,.fa-file-video::before,.fa-external-link-alt::before, .fa-up-right-from-square::before,
.fa-table-cells::before, .fa-th::before,.fa-file-pdf::before,.fa-bible::before, .fa-book-bible::before,.fa-o::before,.fa-medkit::before, .fa-suitcase-medical::before,.fa-user-secret::before,.fa-otter::before,.fa-female::before, .fa-person-dress::before,.fa-comment-dollar::before,.fa-briefcase-clock::before, .fa-business-time::before,.fa-table-cells-large::before, .fa-th-large::before,.fa-book-tanakh::before, .fa-tanakh::before,.fa-phone-volume::before, .fa-volume-control-phone::before,.fa-hat-cowboy-side::before,.fa-clipboard-user::before,.fa-child::before,.fa-lira-sign::before,.fa-satellite::before,.fa-plane-lock::before,.fa-tag::before,.fa-comment::before,.fa-birthday-cake::before, .fa-cake-candles::before, .fa-cake::before,.fa-envelope::before,.fa-angle-double-up::before, .fa-angles-up::before,.fa-paperclip::before,.fa-arrow-right-to-city::before,.fa-ribbon::before,.fa-lungs::before,.fa-arrow-up-9-1::before, .fa-sort-numeric-up-alt::before,.fa-litecoin-sign::before,.fa-border-none::before,.fa-circle-nodes::before,
.fa-parachute-box::before,.fa-indent::before,.fa-truck-field-un::before,.fa-hourglass-empty::before, .fa-hourglass::before,.fa-mountain::before,.fa-user-doctor::before, .fa-user-md::before,.fa-circle-info::before, .fa-info-circle::before,.fa-cloud-meatball::before,.fa-camera-alt::before, .fa-camera::before,.fa-square-virus::before,.fa-meteor::before,.fa-car-on::before,.fa-sleigh::before,.fa-arrow-down-1-9::before, .fa-sort-numeric-asc::before, .fa-sort-numeric-down::before,.fa-hand-holding-droplet::before, .fa-hand-holding-water::before,.fa-water::before,.fa-calendar-check::before,.fa-braille::before,.fa-prescription-bottle-alt::before, .fa-prescription-bottle-medical::before,.fa-landmark::before,.fa-truck::before,.fa-crosshairs::before,.fa-person-cane::before,.fa-tent::before,.fa-vest-patches::before,.fa-check-double::before,.fa-arrow-down-a-z::before, .fa-sort-alpha-asc::before, .fa-sort-alpha-down::before,.fa-money-bill-wheat::before,.fa-cookie::before,.fa-arrow-left-rotate::before, .fa-arrow-rotate-back::before, .fa-arrow-rotate-backward::before, .fa-arrow-rotate-left::before, .fa-undo::before,.fa-hard-drive::before, .fa-hdd::before,.fa-face-grin-squint-tears::before, .fa-grin-squint-tears::before,
.fa-dumbbell::before,.fa-list-alt::before, .fa-rectangle-list::before,.fa-tarp-droplet::before,.fa-house-medical-circle-check::before,.fa-person-skiing-nordic::before, .fa-skiing-nordic::before,.fa-calendar-plus::before,.fa-plane-arrival::before,.fa-arrow-alt-circle-left::before, .fa-circle-left::before,.fa-subway::before, .fa-train-subway::before,.fa-chart-gantt::before,.fa-indian-rupee-sign::before, .fa-indian-rupee::before, .fa-inr::before,.fa-crop-alt::before, .fa-crop-simple::before,.fa-money-bill-1::before, .fa-money-bill-alt::before,.fa-left-long::before, .fa-long-arrow-alt-left::before,.fa-dna::before,.fa-virus-slash::before,.fa-minus::before, .fa-subtract::before,.fa-chess::before,.fa-arrow-left-long::before, .fa-long-arrow-left::before,.fa-plug-circle-check::before,.fa-street-view::before,.fa-franc-sign::before,.fa-volume-off::before,.fa-american-sign-language-interpreting::before, .fa-asl-interpreting::before, .fa-hands-american-sign-language-interpreting::before, .fa-hands-asl-interpreting::before,.fa-cog::before, .fa-gear::before,.fa-droplet-slash::before, .fa-tint-slash::before,.fa-mosque::before,.fa-mosquito::before,.fa-star-of-david::before,.fa-person-military-rifle::before,.fa-cart-shopping::before, .fa-shopping-cart::before,.fa-vials::before,
.fa-plug-circle-plus::before,.fa-place-of-worship::before,.fa-grip-vertical::before,.fa-arrow-turn-up::before, .fa-level-up::before,.fa-u::before,.fa-square-root-alt::before, .fa-square-root-variable::before,.fa-clock-four::before, .fa-clock::before,.fa-backward-step::before, .fa-step-backward::before,.fa-pallet::before,.fa-faucet::before,.fa-baseball-bat-ball::before,.fa-s::before,.fa-timeline::before,.fa-keyboard::before,.fa-caret-down::before,.fa-clinic-medical::before, .fa-house-chimney-medical::before,.fa-temperature-3::before, .fa-temperature-three-quarters::before, .fa-thermometer-3::before, .fa-thermometer-three-quarters::before,.fa-mobile-android-alt::before, .fa-mobile-screen::before,.fa-plane-up::before,.fa-piggy-bank::before,.fa-battery-3::before, .fa-battery-half::before,.fa-mountain-city::before,.fa-coins::before,.fa-khanda::before,.fa-sliders-h::before, .fa-sliders::before,.fa-folder-tree::before,.fa-network-wired::before,.fa-map-pin::before,.fa-hamsa::before,.fa-cent-sign::before,.fa-flask::before,.fa-person-pregnant::before,
.fa-wand-sparkles::before,.fa-ellipsis-v::before, .fa-ellipsis-vertical::before,.fa-ticket::before,.fa-power-off::before,.fa-long-arrow-alt-right::before, .fa-right-long::before,.fa-flag-usa::before,.fa-laptop-file::before,.fa-teletype::before, .fa-tty::before,.fa-diagram-next::before,.fa-person-rifle::before,.fa-house-medical-circle-exclamation::before,.fa-closed-captioning::before,.fa-hiking::before, .fa-person-hiking::before,.fa-venus-double::before,.fa-images::before,.fa-calculator::before,.fa-people-pulling::before,.fa-n::before,.fa-cable-car::before, .fa-tram::before,.fa-cloud-rain::before,.fa-building-circle-xmark::before,.fa-ship::before,.fa-arrows-down-to-line::before,.fa-download::before,.fa-face-grin::before, .fa-grin::before,.fa-backspace::before, .fa-delete-left::before,.fa-eye-dropper-empty::before, .fa-eye-dropper::before, .fa-eyedropper::before,.fa-file-circle-check::before,.fa-forward::before,.fa-mobile-android::before, .fa-mobile-phone::before, .fa-mobile::before,.fa-face-meh::before, .fa-meh::before,.fa-align-center::before,
.fa-book-dead::before, .fa-book-skull::before,.fa-drivers-license::before, .fa-id-card::before,.fa-dedent::before, .fa-outdent::before,.fa-heart-circle-exclamation::before,.fa-home-alt::before, .fa-home-lg-alt::before, .fa-home::before, .fa-house::before,.fa-calendar-week::before,.fa-laptop-medical::before,.fa-b::before,.fa-file-medical::before,.fa-dice-one::before,.fa-kiwi-bird::before,.fa-arrow-right-arrow-left::before, .fa-exchange::before,.fa-redo-alt::before, .fa-rotate-forward::before, .fa-rotate-right::before,.fa-cutlery::before, .fa-utensils::before,.fa-arrow-up-wide-short::before, .fa-sort-amount-up::before,.fa-mill-sign::before,.fa-bowl-rice::before,.fa-skull::before,.fa-broadcast-tower::before, .fa-tower-broadcast::before,.fa-truck-pickup::before,.fa-long-arrow-alt-up::before, .fa-up-long::before,.fa-stop::before,.fa-code-merge::before,.fa-upload::before,.fa-hurricane::before,.fa-mound::before,.fa-toilet-portable::before,.fa-compact-disc::before,.fa-file-arrow-down::before, .fa-file-download::before,.fa-caravan::before,.fa-shield-cat::before,.fa-bolt::before, .fa-zap::before,
.fa-glass-water::before,.fa-oil-well::before,.fa-vault::before,.fa-mars::before,.fa-toilet::before,.fa-plane-circle-xmark::before,.fa-cny::before, .fa-jpy::before, .fa-rmb::before, .fa-yen-sign::before, .fa-yen::before,.fa-rouble::before, .fa-rub::before, .fa-ruble-sign::before, .fa-ruble::before,.fa-sun::before,.fa-guitar::before,.fa-face-laugh-wink::before, .fa-laugh-wink::before,.fa-horse-head::before,.fa-bore-hole::before,.fa-industry::before,.fa-arrow-alt-circle-down::before, .fa-circle-down::before,.fa-arrows-turn-to-dots::before,.fa-florin-sign::before,.fa-arrow-down-short-wide::before, .fa-sort-amount-desc::before, .fa-sort-amount-down-alt::before,.fa-less-than::before,.fa-angle-down::before,.fa-car-tunnel::before,.fa-head-side-cough::before,.fa-grip-lines::before,.fa-thumbs-down::before,.fa-user-lock::before,.fa-arrow-right-long::before, .fa-long-arrow-right::before,.fa-anchor-circle-xmark::before,.fa-ellipsis-h::before, .fa-ellipsis::before,.fa-chess-pawn::before,.fa-first-aid::before, .fa-kit-medical::before,.fa-person-through-window::before,.fa-toolbox::before,
.fa-hands-holding-circle::before,.fa-bug::before,.fa-credit-card-alt::before, .fa-credit-card::before,.fa-automobile::before, .fa-car::before,.fa-hand-holding-hand::before,.fa-book-open-reader::before, .fa-book-reader::before,.fa-mountain-sun::before,.fa-arrows-left-right-to-line::before,.fa-dice-d20::before,.fa-truck-droplet::before,.fa-file-circle-xmark::before,.fa-temperature-arrow-up::before, .fa-temperature-up::before,.fa-medal::before,.fa-bed::before,.fa-h-square::before, .fa-square-h::before,.fa-podcast::before,.fa-temperature-4::before, .fa-temperature-full::before, .fa-thermometer-4::before, .fa-thermometer-full::before,.fa-bell::before,.fa-superscript::before,.fa-plug-circle-xmark::before,.fa-star-of-life::before,.fa-phone-slash::before,.fa-paint-roller::before,.fa-hands-helping::before, .fa-handshake-angle::before,.fa-location-dot::before, .fa-map-marker-alt::before,.fa-file::before,.fa-greater-than::before,.fa-person-swimming::before, .fa-swimmer::before,.fa-arrow-down::before,.fa-droplet::before, .fa-tint::before,.fa-eraser::before,.fa-earth-america::before, .fa-earth-americas::before, .fa-earth::before, .fa-globe-americas::before,
.fa-person-burst::before,.fa-dove::before,.fa-battery-0::before, .fa-battery-empty::before,.fa-socks::before,.fa-inbox::before,.fa-section::before,.fa-gauge-high::before, .fa-tachometer-alt-fast::before, .fa-tachometer-alt::before,.fa-envelope-open-text::before,.fa-hospital-alt::before, .fa-hospital-wide::before, .fa-hospital::before,.fa-wine-bottle::before,.fa-chess-rook::before,.fa-bars-staggered::before, .fa-reorder::before, .fa-stream::before,.fa-dharmachakra::before,.fa-hotdog::before,.fa-blind::before, .fa-person-walking-with-cane::before,.fa-drum::before,.fa-ice-cream::before,.fa-heart-circle-bolt::before,.fa-fax::before,.fa-paragraph::before,.fa-check-to-slot::before, .fa-vote-yea::before,.fa-star-half::before,.fa-boxes-alt::before, .fa-boxes-stacked::before, .fa-boxes::before,.fa-chain::before, .fa-link::before,.fa-assistive-listening-systems::before, .fa-ear-listen::before,.fa-tree-city::before,.fa-play::before,.fa-font::before,.fa-rupiah-sign::before,.fa-magnifying-glass::before, .fa-search::before,.fa-ping-pong-paddle-ball::before, .fa-table-tennis-paddle-ball::before, .fa-table-tennis::before,.fa-diagnoses::before, .fa-person-dots-from-line::before,
.fa-trash-can-arrow-up::before, .fa-trash-restore-alt::before,.fa-naira-sign::before,.fa-cart-arrow-down::before,.fa-walkie-talkie::before,.fa-file-edit::before, .fa-file-pen::before,.fa-receipt::before,.fa-pen-square::before, .fa-pencil-square::before, .fa-square-pen::before,.fa-suitcase-rolling::before,.fa-person-circle-exclamation::before,.fa-chevron-down::before,.fa-battery-5::before, .fa-battery-full::before, .fa-battery::before,.fa-skull-crossbones::before,.fa-code-compare::before,.fa-list-dots::before, .fa-list-ul::before,.fa-school-lock::before,.fa-tower-cell::before,.fa-down-long::before, .fa-long-arrow-alt-down::before,.fa-ranking-star::before,.fa-chess-king::before,.fa-person-harassing::before,.fa-brazilian-real-sign::before,.fa-landmark-alt::before, .fa-landmark-dome::before,.fa-arrow-up::before,.fa-television::before, .fa-tv-alt::before, .fa-tv::before,.fa-shrimp::before,.fa-list-check::before, .fa-tasks::before,.fa-jug-detergent::before,.fa-circle-user::before, .fa-user-circle::before,.fa-user-shield::before,.fa-wind::before,.fa-car-burst::before, .fa-car-crash::before,.fa-y::before,
.fa-person-snowboarding::before, .fa-snowboarding::before,.fa-shipping-fast::before, .fa-truck-fast::before,.fa-fish::before,.fa-user-graduate::before,.fa-adjust::before, .fa-circle-half-stroke::before,.fa-clapperboard::before,.fa-circle-radiation::before, .fa-radiation-alt::before,.fa-baseball-ball::before, .fa-baseball::before,.fa-jet-fighter-up::before,.fa-diagram-project::before, .fa-project-diagram::before,.fa-copy::before,.fa-volume-mute::before, .fa-volume-times::before, .fa-volume-xmark::before,.fa-hand-sparkles::before,.fa-grip-horizontal::before, .fa-grip::before,.fa-share-from-square::before, .fa-share-square::before,.fa-child-combatant::before, .fa-child-rifle::before,.fa-gun::before,.fa-phone-square::before, .fa-square-phone::before,.fa-add::before, .fa-plus::before,.fa-expand::before,.fa-computer::before,.fa-close::before, .fa-multiply::before, .fa-remove::before, .fa-times::before, .fa-xmark::before,.fa-arrows-up-down-left-right::before, .fa-arrows::before,.fa-chalkboard-teacher::before, .fa-chalkboard-user::before,.fa-peso-sign::before,.fa-building-shield::before,.fa-baby::before,.fa-users-line::before,.fa-quote-left-alt::before, .fa-quote-left::before,.fa-tractor::before,.fa-trash-arrow-up::before, .fa-trash-restore::before,.fa-arrow-down-up-lock::before,
.fa-lines-leaning::before,.fa-ruler-combined::before,.fa-copyright::before,.fa-equals::before,.fa-blender::before,.fa-teeth::before,.fa-ils::before, .fa-shekel-sign::before, .fa-shekel::before, .fa-sheqel-sign::before, .fa-sheqel::before,.fa-map::before,.fa-rocket::before,.fa-photo-film::before, .fa-photo-video::before,.fa-folder-minus::before,.fa-store::before,.fa-arrow-trend-up::before,.fa-plug-circle-minus::before,.fa-sign-hanging::before, .fa-sign::before,.fa-bezier-curve::before,.fa-bell-slash::before,.fa-tablet-android::before, .fa-tablet::before,.fa-school-flag::before,.fa-fill::before,.fa-angle-up::before,.fa-drumstick-bite::before,.fa-holly-berry::before,.fa-chevron-left::before,.fa-bacteria::before,.fa-hand-lizard::before,.fa-notdef::before,.fa-disease::before,.fa-briefcase-medical::before,.fa-genderless::before,.fa-chevron-right::before,.fa-retweet::before,
.fa-car-alt::before, .fa-car-rear::before,.fa-pump-soap::before,.fa-video-slash::before,.fa-battery-2::before, .fa-battery-quarter::before,.fa-radio::before,.fa-baby-carriage::before, .fa-carriage-baby::before,.fa-traffic-light::before,.fa-thermometer::before,.fa-vr-cardboard::before,.fa-hand-middle-finger::before,.fa-percent::before, .fa-percentage::before,.fa-truck-moving::before,.fa-glass-water-droplet::before,.fa-display::before,.fa-face-smile::before, .fa-smile::before,.fa-thumb-tack::before, .fa-thumbtack::before,.fa-trophy::before,.fa-person-praying::before, .fa-pray::before,.fa-hammer::before,.fa-hand-peace::before,.fa-rotate::before, .fa-sync-alt::before,.fa-spinner::before,.fa-robot::before,.fa-peace::before,.fa-cogs::before, .fa-gears::before,.fa-warehouse::before,.fa-arrow-up-right-dots::before,.fa-splotch::before,.fa-face-grin-hearts::before, .fa-grin-hearts::before,.fa-dice-four::before,.fa-sim-card::before,.fa-transgender-alt::before, .fa-transgender::before,
.fa-mercury::before,.fa-arrow-turn-down::before, .fa-level-down::before,.fa-person-falling-burst::before,.fa-award::before,.fa-ticket-alt::before, .fa-ticket-simple::before,.fa-building::before,.fa-angle-double-left::before, .fa-angles-left::before,.fa-qrcode::before,.fa-clock-rotate-left::before, .fa-history::before,.fa-face-grin-beam-sweat::before, .fa-grin-beam-sweat::before,.fa-arrow-right-from-file::before, .fa-file-export::before,.fa-shield-blank::before, .fa-shield::before,.fa-arrow-up-short-wide::before, .fa-sort-amount-up-alt::before,.fa-house-medical::before,.fa-golf-ball-tee::before, .fa-golf-ball::before,.fa-chevron-circle-left::before, .fa-circle-chevron-left::before,.fa-house-chimney-window::before,.fa-pen-nib::before,.fa-tent-arrow-turn-left::before,.fa-tents::before,.fa-magic::before, .fa-wand-magic::before,.fa-dog::before,.fa-carrot::before,.fa-moon::before,.fa-wine-glass-alt::before, .fa-wine-glass-empty::before,.fa-cheese::before,.fa-yin-yang::before,.fa-music::before,.fa-code-commit::before,.fa-temperature-low::before,.fa-biking::before, .fa-person-biking::before,.fa-broom::before,
.fa-shield-heart::before,.fa-gopuram::before,.fa-earth-oceania::before, .fa-globe-oceania::before,.fa-square-xmark::before, .fa-times-square::before, .fa-xmark-square::before,.fa-hashtag::before,.fa-expand-alt::before, .fa-up-right-and-down-left-from-center::before,.fa-oil-can::before,.fa-t::before,.fa-hippo::before,.fa-chart-column::before,.fa-infinity::before,.fa-vial-circle-check::before,.fa-person-arrow-down-to-line::before,.fa-voicemail::before,.fa-fan::before,.fa-person-walking-luggage::before,.fa-arrows-alt-v::before, .fa-up-down::before,.fa-cloud-moon-rain::before,.fa-calendar::before,.fa-trailer::before,.fa-bahai::before, .fa-haykal::before,.fa-sd-card::before,.fa-dragon::before,.fa-shoe-prints::before,.fa-circle-plus::before, .fa-plus-circle::before,.fa-face-grin-tongue-wink::before, .fa-grin-tongue-wink::before,.fa-hand-holding::before,.fa-plug-circle-exclamation::before,.fa-chain-broken::before, .fa-chain-slash::before, .fa-link-slash::before, .fa-unlink::before,.fa-clone::before,.fa-person-walking-arrow-loop-left::before,.fa-arrow-up-z-a::before, .fa-sort-alpha-up-alt::before,
.fa-fire-alt::before, .fa-fire-flame-curved::before,.fa-tornado::before,.fa-file-circle-plus::before,.fa-book-quran::before, .fa-quran::before,.fa-anchor::before,.fa-border-all::before,.fa-angry::before, .fa-face-angry::before,.fa-cookie-bite::before,.fa-arrow-trend-down::before,.fa-feed::before, .fa-rss::before,.fa-draw-polygon::before,.fa-balance-scale::before, .fa-scale-balanced::before,.fa-gauge-simple-high::before, .fa-tachometer-fast::before, .fa-tachometer::before,.fa-shower::before,.fa-desktop-alt::before, .fa-desktop::before,.fa-m::before,.fa-table-list::before, .fa-th-list::before,.fa-comment-sms::before, .fa-sms::before,.fa-book::before,.fa-user-plus::before,.fa-check::before,.fa-battery-4::before, .fa-battery-three-quarters::before,.fa-house-circle-check::before,.fa-angle-left::before,.fa-diagram-successor::before,.fa-truck-arrow-right::before,.fa-arrows-split-up-and-left::before,.fa-fist-raised::before, .fa-hand-fist::before,.fa-cloud-moon::before,.fa-briefcase::before,.fa-person-falling::before,.fa-image-portrait::before, .fa-portrait::before,
.fa-user-tag::before,.fa-rug::before,.fa-earth-europe::before, .fa-globe-europe::before,.fa-cart-flatbed-suitcase::before, .fa-luggage-cart::before,.fa-rectangle-times::before, .fa-rectangle-xmark::before, .fa-times-rectangle::before, .fa-window-close::before,.fa-baht-sign::before,.fa-book-open::before,.fa-book-journal-whills::before, .fa-journal-whills::before,.fa-handcuffs::before,.fa-exclamation-triangle::before, .fa-triangle-exclamation::before, .fa-warning::before,.fa-database::before,.fa-arrow-turn-right::before, .fa-mail-forward::before, .fa-share::before,.fa-bottle-droplet::before,.fa-mask-face::before,.fa-hill-rockslide::before,.fa-exchange-alt::before, .fa-right-left::before,.fa-paper-plane::before,.fa-road-circle-exclamation::before,.fa-dungeon::before,.fa-align-right::before,.fa-money-bill-1-wave::before, .fa-money-bill-wave-alt::before,.fa-life-ring::before,.fa-hands::before, .fa-sign-language::before, .fa-signing::before,.fa-calendar-day::before,.fa-ladder-water::before, .fa-swimming-pool::before, .fa-water-ladder::before,.fa-arrows-up-down::before, .fa-arrows-v::before,.fa-face-grimace::before, .fa-grimace::before,.fa-wheelchair-alt::before, .fa-wheelchair-move::before,.fa-level-down-alt::before, .fa-turn-down::before,.fa-person-walking-arrow-right::before,.fa-envelope-square::before, .fa-square-envelope::before,.fa-dice::before,
.fa-bowling-ball::before,.fa-brain::before,.fa-band-aid::before, .fa-bandage::before,.fa-calendar-minus::before,.fa-circle-xmark::before, .fa-times-circle::before, .fa-xmark-circle::before,.fa-gifts::before,.fa-hotel::before,.fa-earth-asia::before, .fa-globe-asia::before,.fa-id-card-alt::before, .fa-id-card-clip::before,.fa-magnifying-glass-plus::before, .fa-search-plus::before,.fa-thumbs-up::before,.fa-user-clock::before,.fa-allergies::before, .fa-hand-dots::before,.fa-file-invoice::before,.fa-window-minimize::before,.fa-coffee::before, .fa-mug-saucer::before,.fa-brush::before,.fa-mask::before,.fa-magnifying-glass-minus::before, .fa-search-minus::before,.fa-ruler-vertical::before,.fa-user-alt::before, .fa-user-large::before,.fa-train-tram::before,.fa-user-nurse::before,.fa-syringe::before,.fa-cloud-sun::before,.fa-stopwatch-20::before,.fa-square-full::before,.fa-magnet::before,.fa-jar::before,.fa-note-sticky::before, .fa-sticky-note::before,.fa-bug-slash::before,.fa-arrow-up-from-water-pump::before,
.fa-bone::before,.fa-user-injured::before,.fa-face-sad-tear::before, .fa-sad-tear::before,.fa-plane::before,.fa-tent-arrows-down::before,.fa-exclamation::before,.fa-arrows-spin::before,.fa-print::before,.fa-try::before, .fa-turkish-lira-sign::before, .fa-turkish-lira::before,.fa-dollar-sign::before, .fa-dollar::before, .fa-usd::before,.fa-x::before,.fa-magnifying-glass-dollar::before, .fa-search-dollar::before,.fa-users-cog::before, .fa-users-gear::before,.fa-person-military-pointing::before,.fa-bank::before, .fa-building-columns::before, .fa-institution::before, .fa-museum::before, .fa-university::before,.fa-umbrella::before,.fa-trowel::before,.fa-d::before,.fa-stapler::before,.fa-masks-theater::before, .fa-theater-masks::before,.fa-kip-sign::before,.fa-hand-point-left::before,.fa-handshake-alt::before, .fa-handshake-simple::before,.fa-fighter-jet::before, .fa-jet-fighter::before,.fa-share-alt-square::before, .fa-square-share-nodes::before,.fa-barcode::before,.fa-plus-minus::before,.fa-video-camera::before, .fa-video::before,.fa-graduation-cap::before, .fa-mortar-board::before,.fa-hand-holding-medical::before,.fa-person-circle-check::before,.fa-level-up-alt::before, .fa-turn-up::before,
.fa-sr-only, .fa-sr-only-focusable:not(:focus), .sr-only, .sr-only-focusable:not(:focus),:host, :root,.fa-brands, .fab,.fa-monero::before,.fa-hooli::before,.fa-yelp::before,.fa-cc-visa::before,.fa-lastfm::before,.fa-shopware::before,.fa-creative-commons-nc::before,.fa-aws::before,.fa-redhat::before,.fa-yoast::before,.fa-cloudflare::before,.fa-ups::before,.fa-wpexplorer::before,.fa-dyalog::before,.fa-bity::before,.fa-stackpath::before,.fa-buysellads::before,.fa-first-order::before,.fa-modx::before,.fa-guilded::before,.fa-vnv::before,.fa-js-square::before, .fa-square-js::before,.fa-microsoft::before,.fa-qq::before,.fa-orcid::before,.fa-java::before,.fa-invision::before,.fa-creative-commons-pd-alt::before,.fa-centercode::before,
.fa-glide-g::before,.fa-drupal::before,.fa-hire-a-helper::before,.fa-creative-commons-by::before,.fa-unity::before,.fa-whmcs::before,.fa-rocketchat::before,.fa-vk::before,.fa-untappd::before,.fa-mailchimp::before,.fa-css3-alt::before,.fa-reddit-square::before, .fa-square-reddit::before,.fa-vimeo-v::before,.fa-contao::before,.fa-square-font-awesome::before,.fa-deskpro::before,.fa-sistrix::before,.fa-instagram-square::before, .fa-square-instagram::before,.fa-battle-net::before,.fa-the-red-yeti::before,.fa-hacker-news-square::before, .fa-square-hacker-news::before,.fa-edge::before,.fa-napster::before,.fa-snapchat-square::before, .fa-square-snapchat::before,.fa-google-plus-g::before,.fa-artstation::before,.fa-markdown::before,.fa-sourcetree::before,.fa-google-plus::before,.fa-diaspora::before,.fa-foursquare::before,.fa-stack-overflow::before,
.fa-github-alt::before,.fa-phoenix-squadron::before,.fa-pagelines::before,.fa-algolia::before,.fa-red-river::before,.fa-creative-commons-sa::before,.fa-safari::before,.fa-google::before,.fa-font-awesome-alt::before, .fa-square-font-awesome-stroke::before,.fa-atlassian::before,.fa-linkedin-in::before,.fa-digital-ocean::before,.fa-nimblr::before,.fa-chromecast::before,.fa-evernote::before,.fa-hacker-news::before,.fa-creative-commons-sampling::before,.fa-adversal::before,.fa-creative-commons::before,.fa-watchman-monitoring::before,.fa-fonticons::before,.fa-weixin::before,.fa-shirtsinbulk::before,.fa-codepen::before,.fa-git-alt::before,.fa-lyft::before,.fa-rev::before,.fa-windows::before,.fa-wizards-of-the-coast::before,.fa-square-viadeo::before, .fa-viadeo-square::before,.fa-meetup::before,.fa-centos::before,
.fa-adn::before,.fa-cloudsmith::before,.fa-pied-piper-alt::before,.fa-dribbble-square::before, .fa-square-dribbble::before,.fa-codiepie::before,.fa-node::before,.fa-mix::before,.fa-steam::before,.fa-cc-apple-pay::before,.fa-scribd::before,.fa-openid::before,.fa-instalod::before,.fa-expeditedssl::before,.fa-sellcast::before,.fa-square-twitter::before, .fa-twitter-square::before,.fa-r-project::before,.fa-delicious::before,.fa-freebsd::before,.fa-vuejs::before,.fa-accusoft::before,.fa-ioxhost::before,.fa-fonticons-fi::before,.fa-app-store::before,.fa-cc-mastercard::before,.fa-itunes-note::before,.fa-golang::before,.fa-kickstarter::before,.fa-grav::before,.fa-weibo::before,.fa-uncharted::before,.fa-firstdraft::before,.fa-square-youtube::before, .fa-youtube-square::before,
.fa-wikipedia-w::before,.fa-rendact::before, .fa-wpressr::before,.fa-angellist::before,.fa-galactic-republic::before,.fa-nfc-directional::before,.fa-skype::before,.fa-joget::before,.fa-fedora::before,.fa-stripe-s::before,.fa-meta::before,.fa-laravel::before,.fa-hotjar::before,.fa-bluetooth-b::before,.fa-sticker-mule::before,.fa-creative-commons-zero::before,.fa-hips::before,.fa-behance::before,.fa-reddit::before,.fa-discord::before,.fa-chrome::before,.fa-app-store-ios::before,.fa-cc-discover::before,.fa-wpbeginner::before,.fa-confluence::before,.fa-mdb::before,.fa-dochub::before,.fa-accessible-icon::before,.fa-ebay::before,.fa-amazon::before,.fa-unsplash::before,.fa-yarn::before,.fa-square-steam::before, .fa-steam-square::before,
.fa-500px::before,.fa-square-vimeo::before, .fa-vimeo-square::before,.fa-asymmetrik::before,.fa-font-awesome-flag::before, .fa-font-awesome-logo-full::before, .fa-font-awesome::before,.fa-gratipay::before,.fa-apple::before,.fa-hive::before,.fa-gitkraken::before,.fa-keybase::before,.fa-apple-pay::before,.fa-padlet::before,.fa-amazon-pay::before,.fa-github-square::before, .fa-square-github::before,.fa-stumbleupon::before,.fa-fedex::before,.fa-phoenix-framework::before,.fa-shopify::before,.fa-neos::before,.fa-hackerrank::before,.fa-researchgate::before,.fa-swift::before,.fa-angular::before,.fa-speakap::before,.fa-angrycreative::before,.fa-y-combinator::before,.fa-empire::before,.fa-envira::before,.fa-gitlab-square::before, .fa-square-gitlab::before,.fa-studiovinari::before,.fa-pied-piper::before,.fa-wordpress::before,.fa-product-hunt::before,
.fa-firefox::before,.fa-linode::before,.fa-goodreads::before,.fa-odnoklassniki-square::before, .fa-square-odnoklassniki::before,.fa-jsfiddle::before,.fa-sith::before,.fa-themeisle::before,.fa-page4::before,.fa-hashnode::before,.fa-react::before,.fa-cc-paypal::before,.fa-squarespace::before,.fa-cc-stripe::before,.fa-creative-commons-share::before,.fa-bitcoin::before,.fa-keycdn::before,.fa-opera::before,.fa-itch-io::before,.fa-umbraco::before,.fa-galactic-senate::before,.fa-ubuntu::before,.fa-draft2digital::before,.fa-stripe::before,.fa-houzz::before,.fa-gg::before,.fa-dhl::before,.fa-pinterest-square::before, .fa-square-pinterest::before,.fa-xing::before,.fa-blackberry::before,.fa-creative-commons-pd::before,.fa-playstation::before,.fa-quinscape::before,
.fa-less::before,.fa-blogger-b::before,.fa-opencart::before,.fa-vine::before,.fa-paypal::before,.fa-gitlab::before,.fa-typo3::before,.fa-reddit-alien::before,.fa-yahoo::before,.fa-dailymotion::before,.fa-affiliatetheme::before,.fa-pied-piper-pp::before,.fa-bootstrap::before,.fa-odnoklassniki::before,.fa-nfc-symbol::before,.fa-ethereum::before,.fa-speaker-deck::before,.fa-creative-commons-nc-eu::before,.fa-patreon::before,.fa-avianex::before,.fa-ello::before,.fa-gofore::before,.fa-bimobject::before,.fa-facebook-f::before,.fa-google-plus-square::before, .fa-square-google-plus::before,.fa-mandalorian::before,.fa-first-order-alt::before,.fa-osi::before,.fa-google-wallet::before,.fa-d-and-d-beyond::before,.fa-periscope::before,.fa-fulcrum::before,
.fa-cloudscale::before,.fa-forumbee::before,.fa-mizuni::before,.fa-schlix::before,.fa-square-xing::before, .fa-xing-square::before,.fa-bandcamp::before,.fa-wpforms::before,.fa-cloudversify::before,.fa-usps::before,.fa-megaport::before,.fa-magento::before,.fa-spotify::before,.fa-optin-monster::before,.fa-fly::before,.fa-aviato::before,.fa-itunes::before,.fa-cuttlefish::before,.fa-blogger::before,.fa-flickr::before,.fa-viber::before,.fa-soundcloud::before,.fa-digg::before,.fa-tencent-weibo::before,.fa-symfony::before,.fa-maxcdn::before,.fa-etsy::before,.fa-facebook-messenger::before,.fa-audible::before,.fa-think-peaks::before,.fa-bilibili::before,.fa-erlang::before,.fa-cotton-bureau::before,
.fa-dashcube::before,.fa-42-group::before, .fa-innosoft::before,.fa-stack-exchange::before,.fa-elementor::before,.fa-pied-piper-square::before, .fa-square-pied-piper::before,.fa-creative-commons-nd::before,.fa-palfed::before,.fa-superpowers::before,.fa-resolving::before,.fa-xbox::before,.fa-searchengin::before,.fa-tiktok::before,.fa-facebook-square::before, .fa-square-facebook::before,.fa-renren::before,.fa-linux::before,.fa-glide::before,.fa-linkedin::before,.fa-hubspot::before,.fa-deploydog::before,.fa-twitch::before,.fa-ravelry::before,.fa-mixer::before,.fa-lastfm-square::before, .fa-square-lastfm::before,.fa-vimeo::before,.fa-mendeley::before,.fa-uniregistry::before,.fa-figma::before,.fa-creative-commons-remix::before,.fa-cc-amazon-pay::before,.fa-dropbox::before,.fa-instagram::before,.fa-cmplid::before,
.fa-facebook::before,.fa-gripfire::before,.fa-jedi-order::before,.fa-uikit::before,.fa-fort-awesome-alt::before,.fa-phabricator::before,.fa-ussunnah::before,.fa-earlybirds::before,.fa-trade-federation::before,.fa-autoprefixer::before,.fa-whatsapp::before,.fa-slideshare::before,.fa-google-play::before,.fa-viadeo::before,.fa-line::before,.fa-google-drive::before,.fa-servicestack::before,.fa-simplybuilt::before,.fa-bitbucket::before,.fa-imdb::before,.fa-deezer::before,.fa-raspberry-pi::before,.fa-jira::before,.fa-docker::before,.fa-screenpal::before,.fa-bluetooth::before,.fa-gitter::before,.fa-d-and-d::before,.fa-microblog::before,.fa-cc-diners-club::before,.fa-gg-circle::before,.fa-pied-piper-hat::before,
.fa-kickstarter-k::before,.fa-yandex::before,.fa-readme::before,.fa-html5::before,.fa-sellsy::before,.fa-sass::before,.fa-wirsindhandwerk::before, .fa-wsh::before,.fa-buromobelexperte::before,.fa-salesforce::before,.fa-octopus-deploy::before,.fa-medapps::before,.fa-ns8::before,.fa-pinterest-p::before,.fa-apper::before,.fa-fort-awesome::before,.fa-waze::before,.fa-cc-jcb::before,.fa-snapchat-ghost::before, .fa-snapchat::before,.fa-fantasy-flight-games::before,.fa-rust::before,.fa-wix::before,.fa-behance-square::before, .fa-square-behance::before,.fa-supple::before,.fa-rebel::before,.fa-css3::before,.fa-staylinked::before,.fa-kaggle::before,.fa-space-awesome::before,.fa-deviantart::before,.fa-cpanel::before,.fa-goodreads-g::before,.fa-git-square::before, .fa-square-git::before,
.fa-square-tumblr::before, .fa-tumblr-square::before,.fa-trello::before,.fa-creative-commons-nc-jp::before,.fa-get-pocket::before,.fa-perbyte::before,.fa-grunt::before,.fa-weebly::before,.fa-connectdevelop::before,.fa-leanpub::before,.fa-black-tie::before,.fa-themeco::before,.fa-python::before,.fa-android::before,.fa-bots::before,.fa-free-code-camp::before,.fa-hornbill::before,.fa-js::before,.fa-ideal::before,.fa-git::before,.fa-dev::before,.fa-sketch::before,.fa-yandex-international::before,.fa-cc-amex::before,.fa-uber::before,.fa-github::before,.fa-php::before,.fa-alipay::before,.fa-youtube::before,.fa-skyatlas::before,.fa-firefox-browser::before,.fa-replyd::before,.fa-suse::before,
.fa-jenkins::before,.fa-twitter::before,.fa-rockrms::before,.fa-pinterest::before,.fa-buffer::before,.fa-npm::before,.fa-yammer::before,.fa-btc::before,.fa-dribbble::before,.fa-stumbleupon-circle::before,.fa-internet-explorer::before,.fa-telegram-plane::before, .fa-telegram::before,.fa-old-republic::before,.fa-square-whatsapp::before, .fa-whatsapp-square::before,.fa-node-js::before,.fa-edge-legacy::before,.fa-slack-hash::before, .fa-slack::before,.fa-medrt::before,.fa-usb::before,.fa-tumblr::before,.fa-vaadin::before,.fa-quora::before,.fa-reacteurope::before,.fa-medium-m::before, .fa-medium::before,.fa-amilia::before,.fa-mixcloud::before,.fa-flipboard::before,.fa-viacoin::before,.fa-critical-role::before,.fa-sitrox::before,.fa-discourse::before,.fa-joomla::before,
.fa-mastodon::before,.fa-airbnb::before,.fa-wolf-pack-battalion::before,.fa-buy-n-large::before,.fa-gulp::before,.fa-creative-commons-sampling-plus::before,.fa-strava::before,.fa-ember::before,.fa-canadian-maple-leaf::before,.fa-teamspeak::before,.fa-pushed::before,.fa-wordpress-simple::before,.fa-nutritionix::before,.fa-wodu::before,.fa-google-pay::before,.fa-intercom::before,.fa-zhihu::before,.fa-korvue::before,.fa-pix::before,.fa-steam-symbol::before,:host, :root,.fa-regular, .far,:host, :root,.fa-solid, .fas'''

def split(str,delimeter):
    l = []
    t=''
    avoid = 0
    for i in str:
        if i == delimeter:
            t = t.replace(" ", "")
            t = t.replace(".", "")
            if t!="":
                l.append(t)
            t = ""
            avoid = 0
        else:
            if i == ':':
                avoid = 1
            if avoid == 1:
                continue
            t = t+i
    return l


def db(l):
    s = "INSERT INTO `icons` (`title`, `created_at`, `updated_at`) VALUES (%s, %s, %s) "
    pre_text = 'fas'
    arr = []
    for i in l:
        if i == "fab":
            pre_text='fab'
            continue
        if i == "far":
            pre_text='far'
            continue
        arr.append(qv(pre_text,i))
    return arr
        
def qv(pre_text,title):
    return (pre_text+' '+title,'2022-12-30 20:25:45', '2022-12-30 20:25:45')

l = split(txt,",")
arr = db(l)
print(arr)

import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  database="u320118955_test"
)

mycursor = mydb.cursor()

sql = "INSERT INTO `icons` (`title`, `created_at`, `updated_at`) VALUES (%s, %s, %s) "


mycursor.executemany(sql, arr)

mydb.commit()

print(mycursor.rowcount, "record inserted.")